export const wardsByDistrict = {
    'Ba Đình': ['Phúc Xá', 'Trúc Bạch', 'Vĩnh Phúc', 'Cống Vị', 'Liễu Giai', 'Ngọc Hà', 'Nguyễn Trung Trực', 'Quán Thánh', 'Quảng An', 'Thành Công'],
    'Hoàn Kiếm': ['Chương Dương', 'Cửa Đông', 'Cửa Nam', 'Đồng Xuân', 'Hàng Bạc', 'Hàng Bồ', 'Hàng Buồm', 'Hàng Đào', 'Hàng Gai', 'Hàng Mã', 'Hàng Trống', 'Lý Thái Tổ', 'Phan Chu Trinh', 'Tràng Tiền'],
    'Đống Đa': ['Cát Linh', 'Hàng Bột', 'Khâm Thiên', 'Kim Liên', 'Láng Hạ','Láng Thượng', 'Nam Đồng', 'Ngã Tư Sở', 'Phương Liên', 'Phương Mai', 'Quang Trung', 'Quốc Tử Giám', 'Thịnh Quang', 'Trung Liệt', 'Trung Phụng', 'Trung Tự', 'Văn Chương', 'Văn Miếu'],
    'Hai Bà Trưng': ['Bạch Mai', 'Bách Khoa', 'Cầu Dền', 'Đồng Tâm', 'Lê Đại Hành', 'Minh Khai', 'Ngô Thì Nhậm', 'Phố Huế', 'Quỳnh Lôi', 'Quỳnh Mai', 'Thanh Lương', 'Thanh Nhàn', 'Trương Định','Vĩnh Phú', 'Vĩnh Tuy'],
    'Cầu Giấy': ['Dịch Vọng', 'Dịch Vọng Hậu', 'Mai Dịch', 'Nghĩa Đô', 'Nghĩa Tân', 'Quan Hoa', 'Trung Hoà', 'Yên Hoà'],
    'Thanh Xuân': ['Hạ Đình', 'Khương Đình', 'Khương Mai', 'Khương Trung', 'Kim Giang', 'Nhân Chính', 'Phương Liệt', 'Thanh Xuân Bắc', 'Thanh Xuân Nam', 'Thanh Xuân Trung', 'Thượng Đình'],
    'Hoàng Mai': ['Đại Kim', 'Định Công', 'Giáp Bát', 'Hoàng Liệt', 'Hoàng Văn Thụ', 'Lĩnh Nam', 'Linh Đàm', 'Mai Động', 'Tân Mai', 'Thanh Trì', 'Thịnh Liệt', 'Trần Phú', 'Vĩnh Hưng', 'Yên Sở'],
    'Long Biên': ['Bồ Đề', 'Cự Khối', 'Đức Giang', 'Gia Thụy', 'Giang Biên', 'Long Biên', 'Ngọc Lâm', 'Phúc Đồng', 'Phúc Lợi', 'Sài Đồng', 'Thạch Bàn', 'Thượng Thanh', 'Việt Hưng'],
    'Tây Hồ': ['Bưởi', 'Nhật Tân', 'Phú Thượng', 'Quảng An', 'Thụy Khuê', 'Tứ Liên', 'Xuân La', 'Yên Phụ'],
    'Hà Đông': ['Biên Giang', 'Đồng Mai', 'Dương Nội', 'Hà Cầu', 'Kiến Hưng', 'La Khê', 'Mộ Lao', 'Nguyễn Trãi', 'Phú Lãm', 'Phú La', 'Phú Lương', 'Phúc La', 'Quang Trung', 'Văn Quán', 'Vạn Phúc', 'Yên Nghĩa'],
    'Hoài Đức': ['An Khánh', 'An Thượng', 'Cát Quế', 'Đại Mỗ', 'Đông La', 'Đức Thượng', 'Đức Giang', 'Kim Chung', 'Lại Yên', 'Lai Xá', 'Minh Khai', 'Phú Cát', 'Phú Diễn', 'Song Phương', 'Sơn Đồng', 'Tây Mỗ', 'Tiền Yên'],
    'Bắc Từ Liêm': ['Cổ Nhuế 1', 'Cổ Nhuế 2', 'Đông Ngạc', 'Đức Thắng', 'Liên Mạc', 'Minh Khai', 'Phú Diễn', 'Phúc Diễn', 'Tây Tựu', 'Thụy Phương', 'Trung Tựu', 'Xuân Đỉnh', 'Xuân Tảo'],
    'Nam Từ Liêm': ['Cầu Diễn', 'Đại Mỗ', 'Mễ Trì', 'Mỹ Đình 1', 'Mỹ Đình 2', 'Phú Đô', 'Phương Canh', 'Tây Mỗ', 'Trung Văn', 'Xuân Phương'],
    'Sóc Sơn': ['Bắc Phú', 'Bắc Sơn', 'Đông Xuân', 'Hiền Ninh', 'Hồng Kỳ', 'Kim Lũ', 'Mai Đình', 'Minh Phú', 'Minh Trí', 'Nam Sơn', 'Phù Linh', 'Phù Lỗ', 'Phú Cường', 'Phú Minh', 'Quang Tiến', 'Tân Dân', 'Tân Hưng', 'Tân Minh', 'Tân Xuân', 'Thanh Xuân', 'Tiên Dược', 'Trung Giã', 'Việt Long', 'Xuân Giang', 'Xuân Thu'],
    'Đông Anh': ['Bắc Hồng', 'Cổ Loa', 'Đại Mạch', 'Đông Hội', 'Dục Tú', 'Hải Bối', 'Kim Chung', 'Kim Nỗ', 'Liên Hà', 'Mai Lâm', 'Nguyên Khê', 'Tàm Xá', 'Thụy Lâm', 'Tiên Dương', 'Uy Nỗ', 'Vân Hà', 'Vân Nội', 'Vĩnh Ngọc', 'Võng La', 'Xuân Canh', 'Xuân Nộn'],
    'Gia Lâm': ['Bát Tràng', 'Cổ Bi', 'Đa Tốn', 'Đặng Xá', 'Dương Hà', 'Dương Quang', 'Dương Xá', 'Kiêu Kỵ', 'Kim Sơn', 'Lệ Chi', 'Ninh Hiệp', 'Phú Thị', 'Trâu Quỳ', 'Yên Thường', 'Yên Viên'],
    'Thanh Trì': ['Cầu Bươu', 'Đại Áng', 'Đông Mỹ', 'Duyên Hà', 'Hữu Hoà', 'Liên Ninh', 'Ngọc Hồi', 'Tả Thanh Oai', 'Tam Hiệp', 'Tân Triều', 'Thanh Liệt', 'Thanh Trì', 'Thị trấn Văn Điển', 'Vạn Phúc', 'Vĩnh Quỳnh', 'Yên Mỹ'],
    'Mê Linh': ['Chu Phan', 'Đại Thịnh', 'Hoàng Kim', 'Kim Hoa', 'Liên Mạc', 'Mê Linh', 'Tam Đồng', 'Thạch Đà', 'Thanh Lâm', 'Tiền Phong', 'Tráng Việt', 'Tự Lập', 'Văn Khê', 'Vạn Yên'],
  };